'use strict';
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7Z"/>',folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',back:'<path d="M19 12H5m5-5-5 5 5 5"/>',up:'<path d="M12 19V5m-6 6 6-6 6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',circle:'<circle cx="12" cy="12" r="8"/>',clock:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',flag:'<path d="M5 21V3h14l-3 4 3 4H5"/>',alert:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v.1"/>',file:'<path d="M14 2H5v20h14V7Zm0 0v6h5M8 12h8m-8 4h6"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M5.1 7a8 8 0 0 1 13.2-1L20 9M4 15l1.7 3A8 8 0 0 0 19 17"/>',layers:'<path d="m12 3 10 5-10 5L2 8Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',message:'<path d="M21 11a8 8 0 0 1-8 8H5l-3 3V5a2 2 0 0 1 2-2h9a8 8 0 0 1 8 8Z"/>',x:'<path d="m6 6 12 12M6 18 18 6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0v7l-2 3h16l-2-3Zm-8 13h4"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.circle}</svg>`;
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={blocked:'等你决定',review:'待你验收',running:'进行中',waiting:'等待依赖',done:'已完成',todo:'待开始'};
const KEY='chatty.workbench.prototype.v1';
const projects=[{id:'chatty',name:'Chatty',goal:'让 Android 日常工作更顺畅',description:'原生体验、任务追踪与加载速度。'},{id:'automation',name:'自动化工作流',goal:'让重复的工作自动运行',description:'日报整理、环境检查与周期性任务。'}];
function seed(){return{version:1,project:'all',view:'all',drafts:{},messages:{},simulation:0,tasks:[
{id:'queue',project:'chatty',code:'CHT-24',title:'消息排队与中断',status:'review',owner:'开发 Agent',creator:'Mika',summary:'实现和回归验证已完成，等待你确认交互体验。',goal:'在 Mika 忙碌时继续交办，保留草稿，并能调整排队顺序。',update:'提交了交付包和验证记录，已进入待验收。',fresh:true,ago:'8 分钟',artifacts:['交互体验清单','代码改动与验证摘要'],timeline:[{time:'8 分钟前',text:'开发 Agent 提交交付结果，等待 用户 验收。'},{time:'今天 10:20',text:'队列、中断和草稿恢复的验证完成。'},{time:'今天 09:10',text:'Mika 将事项交给开发 Agent。'}]},
{id:'runtime',project:'chatty',code:'CHT-25',title:'接通自动测试环境',status:'blocked',owner:'Mika',creator:'项目成员',summary:'本地 Runtime 与云端均可用，需要你确定执行位置。',goal:'建立一个可重复验证 Android 常用操作的环境。',update:'环境检查完成，执行位置尚未确认。',fresh:true,ago:'12 分钟',artifacts:['环境检查摘要'],timeline:[{time:'12 分钟前',text:'检测到两种可用环境，请 用户 选择。'},{time:'今天 09:45',text:'开始检查本地 Runtime 与云端环境。'}]},
{id:'cache',project:'chatty',code:'CHT-26',title:'项目列表快速恢复',status:'running',owner:'性能 Agent',creator:'项目成员',summary:'正在验证账号切换后的缓存隔离。',goal:'重新打开项目时先恢复已有内容，再同步最新状态。',update:'读取策略已完成，开始验证隔离与失效。',fresh:true,ago:'2 分钟',artifacts:['缓存行为设计'],timeline:[{time:'2 分钟前',text:'开始验证账号与工作区切换。'},{time:'今天 10:05',text:'完成列表恢复与后台更新策略。'}]},
{id:'offline',project:'chatty',code:'CHT-27',title:'弱网下继续查看项目',status:'waiting',owner:'客户端 Agent',creator:'Mika',summary:'等待「项目列表快速恢复」完成后开始联调。',goal:'网络暂时不可用时，仍可查看已有项目内容与本地草稿。',update:'前置事项仍在验证，本项尚未开始。',fresh:false,ago:'25 分钟',dependency:'cache',artifacts:[],timeline:[{time:'25 分钟前',text:'建立对「项目列表快速恢复」的依赖。'}]},
{id:'navigation',project:'chatty',code:'CHT-23',title:'返回详情保留阅读位置',status:'done',owner:'客户端 Agent',creator:'项目成员',summary:'已验收：列表位置、筛选和详情阅读位置均保留。',goal:'离开页面后再次返回，能够从上次位置继续。',update:'交互验收通过，事项完成。',fresh:false,ago:'昨天',artifacts:['验收记录'],timeline:[{time:'昨天',text:'用户 完成交互验收。'}]},
{id:'digest',project:'automation',code:'AUT-08',title:'每天整理项目进展摘要',status:'running',owner:'自动化 Agent',creator:'项目成员',summary:'正在校对跨项目事件的分组和去重。',goal:'把一天内的实质变化整理成可读摘要，保留来源。',update:'已接入示例事件，正在调整汇总规则。',fresh:false,ago:'18 分钟',artifacts:['摘要格式草案'],timeline:[{time:'18 分钟前',text:'开始检查重复事件的合并规则。'}]},
{id:'health',project:'automation',code:'AUT-09',title:'Runtime 可用性检查',status:'done',owner:'自动化 Agent',creator:'Mika',summary:'运行环境检查规则已验证。',goal:'清楚区分离线、繁忙和可用的执行环境。',update:'规则验证完成。',fresh:false,ago:'昨天',artifacts:['检查记录'],timeline:[{time:'昨天',text:'检查规则通过验收。'}]}
]};}
let db;try{db=JSON.parse(localStorage.getItem(KEY));if(!db||db.version!==1||!Array.isArray(db.tasks))db=seed();}catch{db=seed();}
const content=document.getElementById('content'),modalRoot=document.getElementById('modal-root');
let modalReturn=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));}catch{toast('浏览器存储不可用，本次修改仅在当前页面保留。');}}
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500);}
function route(){const parts=location.hash.replace(/^#\//,'').split('/');return{page:parts[0]||'desk',id:parts[1]||null};}
function taskById(id){return db.tasks.find(t=>t.id===id);}
function projectName(id){return projects.find(p=>p.id===id)?.name||'Chatty';}
function scoped(){return db.tasks.filter(t=>db.project==='all'||t.project===db.project);}
function requiresAction(t){return ['review','blocked'].includes(t.status);}
function statusBadge(t){return `<span class="badge ${t.status}">${statuses[t.status]}</span>`;}
function owner(t){return `<span class="owner"><span class="mini-avatar">${escapeHTML(t.owner==='Mika'?'M':t.owner[0])}</span>${escapeHTML(t.owner)}</span>`;}
function projectTag(t){return `<span class="project-tag"><i></i>${escapeHTML(projectName(t.project))}</span>`;}
function selectProject(){return `<select class="project-select" aria-label="项目范围" data-project><option value="all" ${db.project==='all'?'selected':''}>全部项目</option>${projects.map(p=>`<option value="${p.id}" ${db.project===p.id?'selected':''}>${escapeHTML(p.name)}</option>`).join('')}</select>`;}
function nav(){const {page}=route(),total=db.tasks.filter(requiresAction).length;const active=page==='task'?'desk':page;const html=[['desk','grid','工作台'],['mika','spark','Mika'],['projects','folder','项目']].map(([path,name,title])=>`<a class="nav-item ${active===path?'active':''}" href="#/${path}" ${active===path?'aria-current="page"':''}>${icon(name)}<span>${title}</span>${path==='desk'&&total?`<span class="count">${total}</span>`:''}</a>`).join('');document.getElementById('desktop-nav').innerHTML=html;document.getElementById('mobile-nav').innerHTML=html;document.getElementById('breadcrumb').innerHTML=`工作空间 <span>/</span> <strong>${({desk:'工作台',mika:'Mika',projects:'项目',task:'事项详情'})[page]||'工作台'}</strong>`;document.getElementById('talk-link').innerHTML=icon('spark')+'和 Mika 说';document.getElementById('simulate-button').innerHTML=icon('refresh')+'模拟新进展';}
function row(t){const stateIcon={blocked:'alert',review:'flag',running:'clock',waiting:'circle',done:'check',todo:'circle'}[t.status];return `<a href="#/task/${t.id}" class="task-row" data-task-row="${t.id}"><span class="state-icon ${t.status}">${icon(stateIcon)}</span><div class="task-main"><div class="task-title">${escapeHTML(t.title)}${t.fresh?'<span class="unread-dot" aria-label="有未读进展"></span>':''}</div><div class="task-description">${escapeHTML(t.code)} · ${escapeHTML(db.view==='new'?t.update:t.summary)}</div></div><div class="task-trailing">${owner(t)}${statusBadge(t)}<span class="task-time">${escapeHTML(t.ago)}</span></div></a>`;}
function attentionCard(t){return `<a href="#/task/${t.id}" class="attention-card" data-attention="${t.id}"><div class="card-top">${projectTag(t)}${statusBadge(t)}</div><h3>${escapeHTML(t.title)}</h3><p>${escapeHTML(t.summary)}</p><div class="card-foot">${owner(t)}<span class="card-action">${t.status==='review'?'查看并验收':'做出选择'}${icon('arrow')}</span></div></a>`;}
function projectProgress(id){const ts=db.tasks.filter(t=>t.project===id),done=ts.filter(t=>t.status==='done').length,review=ts.filter(t=>t.status==='review').length;return `<div class="project-progress"><span>${escapeHTML(projectName(id))}</span><span>${done} / ${ts.length} 已完成</span></div><div class="progress-track" aria-label="${escapeHTML(projectName(id))}：${done}项已完成，${review}项待验收，其余${ts.length-done-review}项"><span class="done" style="flex:${done}"></span><span class="review" style="flex:${review}"></span><span class="other" style="flex:${ts.length-done-review}"></span></div><div class="progress-caption">${review} 项待验收 · ${ts.filter(t=>t.status==='running').length} 项进行中</div>`;}
function desk(){const tasks=scoped(),attention=tasks.filter(requiresAction),newTasks=tasks.filter(t=>t.fresh),list=db.view==='new'?newTasks:db.view==='action'?attention:tasks;const changed=tasks.filter(t=>t.fresh).slice(0,3);return `<div class="page-heading"><div><div class="eyebrow"><span class="dot"></span> YOUR PROJECTS, MOVING FORWARD</div><h1>${attention.length?'项目在推进，关键一步等你。':'事情正在有序推进。'}</h1><p class="subtitle">不用翻聊天记录，看看现在发生了什么。</p></div>${selectProject()}</div><section class="pulse"><div class="pulse-icon">${icon('spark')}</div><div class="pulse-copy"><h2>${attention.length?`${attention.length} 项需要你推进，${tasks.filter(t=>t.status==='running').length} 项正在进行。`:'当前没有需要你处理的事项。'}</h2><p>${attention.length?attention.slice(0,2).map(t=>escapeHTML(t.status==='review'?`验收「${t.title}」`:`为「${t.title}」做出选择`)).join('；')+'。':'你可以查看最新进展，或向 Mika 交办下一件事。'}</p></div><span class="pulse-meta">项目全局 · 示例状态</span></section><div class="layout"><div><section><div class="section-header"><h2>需要你推进 <span class="number">${attention.length}</span></h2><small>看过之后，仍会保留到处理完成</small></div><div class="attention-grid">${attention.length?attention.map(attentionCard).join(''):'<div class="empty"><strong>没有待处理事项</strong>有新的决策或交付需要你时，会出现在这里。</div>'}</div></section><section><div class="section-header"><h2>所有事项 <span class="number">${tasks.length}</span></h2><small>覆盖所有发起人</small></div><div class="view-tabs" role="group" aria-label="事项视角">${[['all','总览',tasks.length],['new','新进展',newTasks.length],['action','待我处理',attention.length]].map(([v,title,count])=>`<button class="view-tab ${db.view===v?'active':''}" data-view="${v}" aria-pressed="${db.view===v}">${title}<span class="number">${count}</span></button>`).join('')}</div><div class="task-list">${list.length?list.map(row).join(''):'<div class="empty"><strong>这里已经看完了</strong>已读状态不会改变事项的执行或待处理状态。</div>'}</div><p class="footnote">你、项目成员和 Agent 发起的工作，都在同一个项目视图里。</p></section></div><aside class="right-rail"><section class="rail-panel"><h3>${icon('clock')}离开期间的变化</h3>${changed.length?changed.map(t=>`<a class="update" style="display:block" href="#/task/${t.id}"><div class="update-time">${escapeHTML(t.ago)}前 · ${escapeHTML(projectName(t.project))}</div><div class="update-title">${escapeHTML(t.title)}</div><p>${escapeHTML(t.update)}</p></a>`).join(''):'<p class="subtitle">你已看过当前所有新进展。</p>'}<button class="quiet-button rail-action" data-action="show-new">查看全部变化 →</button></section><section class="rail-panel"><h3>${icon('layers')}项目概况</h3>${projects.filter(p=>db.project==='all'||p.id===db.project).map(p=>`<div style="margin-bottom:23px">${projectProgress(p.id)}</div>`).join('')}<a href="#/projects" class="rail-action">进入项目 →</a></section></aside></div>`;}
function taskDetail(t){return `<a href="#/desk" class="back-link">${icon('back')}返回工作台</a><div class="detail-heading"><div class="eyebrow">${escapeHTML(projectName(t.project))} <span>/</span> ${escapeHTML(t.code)}</div><h1>${escapeHTML(t.title)}</h1><div class="meta">${statusBadge(t)}${owner(t)}<span>发起：${escapeHTML(t.creator)}</span><span>${t.status==='done'?'事项已完成':requiresAction(t)?'已读 · 仍待你处理':'已读 · 持续跟踪'}</span></div></div><div class="detail-layout"><div><section class="paper"><h2>现在的情况</h2><div class="key-result"><label>${t.status==='review'?'结果已经准备好':t.status==='blocked'?'需要一个明确的决定':'当前进展'}</label><p>${escapeHTML(t.summary)}</p></div><h2>这件事要完成什么</h2><p>${escapeHTML(t.goal)}</p>${t.dependency?`<p>前置事项：<a class="inline-link" href="#/task/${t.dependency}">${escapeHTML(taskById(t.dependency)?.title||'查看依赖')}</a></p>`:''}${t.notes?.length?`<h2 style="margin-top:23px">补充要求</h2>${t.notes.map(n=>`<p class="decision-note">${escapeHTML(n)}</p>`).join('')}`:''}<div class="detail-actions">${t.status==='review'?`<button class="button primary" data-action="approve" data-id="${t.id}">${icon('check')}验收通过</button><button class="button" data-action="revise" data-id="${t.id}">提出修改</button>`:t.status==='blocked'?`<button class="button primary" data-action="decide" data-id="${t.id}">选择执行环境${icon('arrow')}</button>`:''}<a class="button ${requiresAction(t)?'':'primary'}" href="#/mika/${t.id}">${icon('spark')}围绕这件事问 Mika</a></div></section><section class="paper"><h2>交付与证据 <span class="number">${t.artifacts.length}</span></h2>${t.artifacts.length?t.artifacts.map((a,i)=>`<button class="artifact" style="width:100%;background:white;text-align:left" data-action="artifact" data-id="${t.id}" data-index="${i}">${icon('file')}<span>${escapeHTML(a)}<small>本次事项关联的示例记录</small></span>${icon('arrow')}</button>`).join(''):'<p>事项尚未提交交付物。提交后会在这里持续保留。</p>'}</section></div><aside class="detail-aside"><section class="paper"><h2>事项信息</h2><dl class="details-grid"><dt>所属项目</dt><dd>${escapeHTML(projectName(t.project))}</dd><dt>负责人</dt><dd>${escapeHTML(t.owner)}</dd><dt>发起人</dt><dd>${escapeHTML(t.creator)}</dd><dt>状态</dt><dd>${statuses[t.status]}</dd><dt>跟踪方式</dt><dd>项目全局</dd></dl></section><section class="paper"><h2>进展记录</h2>${t.timeline.map(e=>`<div class="timeline-line"><span class="time">${escapeHTML(e.time)}</span><p>${escapeHTML(e.text)}</p></div>`).join('')}</section></aside></div>`;}
function projectPage(){return `<div class="page-heading"><div><div class="eyebrow">CONNECTED WORK</div><h1>把每件事，放回项目里。</h1><p class="subtitle">跨发起人、跨 Agent，持续追踪共同的目标。</p></div><button class="button quiet" data-action="reset">重置体验</button></div><div class="project-grid">${projects.map(p=>{const ts=db.tasks.filter(t=>t.project===p.id);return `<a class="project-card" href="#/desk" data-open-project="${p.id}"><div class="project-logo">${icon(p.id==='chatty'?'message':'layers')}</div><h2>${escapeHTML(p.name)}</h2><p>${escapeHTML(p.goal)}</p>${projectProgress(p.id)}<div class="project-meta"><span>${ts.filter(requiresAction).length} 项需要你</span><span>${ts.filter(t=>t.fresh).length} 项新进展</span></div></a>`;}).join('')}</div>`;}
function chatKey(id){return id||'global';}
function receipt(id){const t=taskById(id);if(!t)return '';return `<a href="#/task/${t.id}" class="receipt"><span class="receipt-label">${icon('check')}已建立可追踪事项</span><h3>${escapeHTML(t.title)}</h3><p>${escapeHTML(projectName(t.project))} · 负责：${escapeHTML(t.owner)} · ${statuses[t.status]}</p><div class="receipt-foot">查看事项与后续进展${icon('arrow')}</div></a>`;}
function messageHTML(m){return `<div class="message ${m.role}">${m.role==='assistant'?'<span class="mini-avatar">M</span>':''}<div class="message-body">${m.role==='assistant'?'<div class="message-label">Mika · 示例回应</div>':''}<div class="bubble">${escapeHTML(m.text)}</div>${m.task?receipt(m.task):''}${m.link?`<a href="#/task/${m.link}" class="inline-link">查看当前事项 →</a>`:''}${m.offer?`<button class="button" style="margin-top:12px" data-action="track" data-text="${escapeHTML(m.offer)}">将这条要求交办给 Mika</button>`:''}</div></div>`;}
function mikaPage(id){const t=taskById(id),key=chatKey(t?.id),messages=db.messages[key]||[];const draft=db.drafts[key]||'';return `<div class="chat-layout"><div class="chat-heading"><div class="mika-avatar">${icon('spark')}</div><div><h1>Mika</h1><p>探索想法，交办事情，接着上次继续。</p></div></div><div class="conversation" id="conversation">${messages.length?'<div class="day-divider">当前浏览器的体验记录</div>'+messages.map(messageHTML).join(''):`<div class="chat-welcome"><div class="mika-avatar">${icon('spark')}</div><h2>${t?'接着这件事，继续。':'今天，想推进什么？'}</h2><p>${t?'补充要求、追问进度，都会留在同一个事项里。':'可以先讨论，也可以直接交办。我会把需要推进的事记录下来。'}</p><div class="suggestions">${(t?['这件事现在卡在哪里？','补充要求：先验证弱网场景']:['项目现在有哪些事情等我处理？','缓存有哪些方案？','帮我优化项目列表的加载速度']).map(s=>`<button class="suggestion" data-prompt="${escapeHTML(s)}">${escapeHTML(s)}</button>`).join('')}</div></div>`}</div><form class="composer" id="chat-form">${t?`<div class="context-pill"><span>${icon('file')} 正在讨论：${escapeHTML(t.title)}</span><a href="#/mika" aria-label="回到全局 Mika 对话">${icon('x')}</a></div>`:`<div class="context-pill"><span>交办到：${escapeHTML(projectName(db.project==='all'?'chatty':db.project))}</span><select class="project-select" data-chat-project aria-label="交办所属项目">${projects.map(p=>`<option value="${p.id}" ${(db.project==='all'?'chatty':db.project)===p.id?'selected':''}>${escapeHTML(p.name)}</option>`).join('')}</select></div>`}<textarea id="chat-input" name="message" rows="2" aria-label="给 Mika 的消息" placeholder="${t?'补充要求，或问问接下来怎么推进…':'和 Mika 说说你的想法…'}">${escapeHTML(draft)}</textarea><div class="composer-bottom"><small>${t?'讨论与补充要求会留在当前事项':'讨论不会自动建档，明确交办会生成事项卡片'}</small><button type="submit" class="send-button" aria-label="发送给 Mika">${icon('up')}</button></div></form><p class="chat-caption">交互体验版 · 本地演示回应，不连接真实 AI 或执行任务</p></div>`;}
function render(){const r=route();nav();if(r.page==='task'){const t=taskById(r.id);if(t){if(t.fresh){t.fresh=false;save();}content.innerHTML=taskDetail(t);}else content.innerHTML='<div class="empty"><strong>这件事项不存在</strong><a href="#/desk">返回工作台</a></div>';}else if(r.page==='mika')content.innerHTML=mikaPage(r.id);else if(r.page==='projects')content.innerHTML=projectPage();else content.innerHTML=desk();}
function addEvent(t,text){t.timeline.unshift({time:'刚刚',text});t.update=text;t.ago='刚刚';}
function createTask(text,project){const title=text.replace(/^(?:另外|此外|新事项|单独)[:：，,\s]*/,'').replace(/^(?:帮我|请帮我|请|麻烦你|开始|执行|实现|开发)[，,\s]*/,'').replace(/[。！？!?.]+$/,'').trim()||'新的项目事项';const t={id:'task-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,5),code:'NEW-'+(db.tasks.filter(t=>t.id.startsWith('task-')).length+1),project:project||'chatty',title:title.slice(0,70),goal:text,status:'todo',owner:'Mika',creator:'用户',summary:'交办已经记录，等待 Mika 整理执行方案。',update:'已建立事项，原始要求与项目归属已保留。',fresh:false,ago:'刚刚',artifacts:[],timeline:[{time:'刚刚',text:'用户 通过 Mika 交办，事项已建档。'}]};db.tasks.unshift(t);return t;}
function send(text,forced=false){text=text.trim();if(!text)return;const r=route(),context=taskById(r.id),key=chatKey(context?.id);db.messages[key]||=[];db.messages[key].push({role:'user',text});db.drafts[key]='';let response;
const explicit=/^(?:帮我|请帮我|请|麻烦|交办|执行|开始|新事项|另外帮我|另外请|单独|把.+(?:做|改|优化))/.test(text)&&!/(?:什么|怎么|如何|有哪些|方案[？?]|思路[？?]|可以吗[？?]?)$/.test(text);
if(context&&!/^(?:另外|此外|新事项|单独)/.test(text)){
if(/补充|要求|改成|优先|先验证|请先|帮我/.test(text)){context.notes||=[];context.notes.push(text);addEvent(context,'补充要求已加入当前事项：'+text);response={text:'已把这条要求补充到「'+context.title+'」。\n后续讨论、执行记录与结果都会继续保留在同一事项中。',link:context.id};}
else response={text:'「'+context.title+'」目前'+statuses[context.status]+'。\n'+context.summary+'\n\n负责：'+context.owner+'。'+(context.dependency?'前置依赖：'+taskById(context.dependency)?.title+'。':requiresAction(context)?'你可以从事项详情完成当前决定或验收。':'有实质进展时会显示在工作台。'),link:context.id};
}else if(forced||explicit){const t=createTask(text,context?.project||(db.project==='all'?'chatty':db.project));response={text:'交办已记录。我把它放进了项目，后续可以从工作台持续跟踪。',task:t.id};}
else if(/(?:项目|事项|任务|进度|卡住|处理|在忙)/.test(text)&&!/(?:缓存|方案)/.test(text)){const pending=scoped().filter(requiresAction);response={text:pending.length?`当前有 ${pending.length} 项需要你推进：\n`+pending.map(t=>'• '+t.title+'：'+t.summary).join('\n'):'当前没有需要你处理的事项。进行中的工作仍在工作台持续展示。'};}
else if(/缓存|方案|思路/.test(text)){response={text:'可以先把等待分成两部分来看：重复获取数据，以及页面重新绘制。\n\n对项目列表，可以保留上次内容、后台刷新最新状态，并按账号和工作区隔离缓存。先测实际等待来自哪里，再选择最小改动。\n\n这轮保持讨论；当你明确说“帮我优化……”时，我会为它建立可追踪事项。'};}
else response={text:'这条内容先留在讨论里。\n如果希望持续推进，可以直接补充“帮我完成……”及希望得到的结果，我会给出事项回执。',offer:text};
db.messages[key].push({role:'assistant',...response});save();render();requestAnimationFrame(()=>{const input=document.getElementById('chat-input');input?.focus({preventScroll:true});document.querySelector('.message:last-child')?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});}
function openModal(html){modalReturn=document.activeElement;modalRoot.innerHTML=`<div class="modal-overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">${html}</section></div>`;const focus=modalRoot.querySelector('textarea,input,button');focus?.focus();}
function closeModal(){modalRoot.innerHTML='';if(modalReturn&&document.contains(modalReturn))modalReturn.focus();}
function simulate(){const tasks=scoped();const candidate=tasks.find(t=>t.status==='todo')||tasks.find(t=>t.status==='running')||tasks.find(t=>t.status==='waiting');if(!candidate){toast('当前没有可推进的示例任务，可以先向 Mika 交办一件事。');return;}if(candidate.status==='todo'){candidate.status='running';candidate.summary='已经开始整理方案与验证路径。';addEvent(candidate,'Mika 开始推进事项，已进入执行阶段。');}else if(candidate.status==='running'){candidate.status='review';candidate.summary='示例交付结果已准备好，等待你验收。';candidate.artifacts.push('本轮交付与验证记录');addEvent(candidate,'执行结果已提交，事项进入待验收。');}else{const dep=taskById(candidate.dependency);if(dep&&dep.status!=='done'){candidate.fresh=true;addEvent(candidate,'前置事项仍未完成，本项继续等待依赖。');}else{candidate.status='running';candidate.summary='依赖已满足，开始联调与验证。';addEvent(candidate,'依赖已解除，开始执行。');}}candidate.fresh=true;db.simulation++;save();render();toast('新进展：'+candidate.title+' · '+statuses[candidate.status]);}
document.addEventListener('click',e=>{
const projectLink=e.target.closest('[data-open-project]');if(projectLink){db.project=projectLink.dataset.openProject;db.view='all';save();if(route().page==='desk')render();}
const b=e.target.closest('[data-action],[data-view],[data-prompt]');if(!b)return;
if(b.dataset.view){db.view=b.dataset.view;save();render();return;}
if(b.dataset.prompt){send(b.dataset.prompt);return;}
const id=b.dataset.id,t=taskById(id);
switch(b.dataset.action){
case 'show-new':db.view='new';save();render();break;
case 'simulate':simulate();break;
case 'reset':openModal('<h2 id="modal-title">重新体验这套工作方式</h2><p>将清除当前浏览器里的示例聊天和新建事项，恢复初始场景。</p><div class="actions"><button class="button" data-action="close-modal">保留记录</button><button class="button primary" data-action="confirm-reset">重置体验</button></div>');break;
case 'confirm-reset':db=seed();save();closeModal();location.hash='#/desk';render();toast('已恢复初始体验');break;
case 'close-modal':closeModal();break;
case 'approve':openModal(`<h2 id="modal-title">验收这件事项</h2><p>${escapeHTML(t.title)}</p><label>验收说明（选填）<textarea id="approval-note" rows="3" placeholder="哪些结果符合预期？"></textarea></label><div class="actions"><button class="button" data-action="close-modal">再看看</button><button class="button primary" data-action="confirm-approve" data-id="${t.id}">确认验收通过</button></div>`);break;
case 'confirm-approve':{const note=document.getElementById('approval-note').value.trim();t.status='done';t.summary='已验收：'+(note||'交付结果符合预期。');t.fresh=false;addEvent(t,'用户 验收通过。'+note);db.tasks.filter(x=>x.dependency===t.id&&x.status==='waiting').forEach(x=>{x.status='todo';x.summary='前置事项已完成，可以开始。';x.fresh=true;addEvent(x,'前置事项已验收，等待开始。');});save();closeModal();render();toast('已验收，事项已移出待处理');break;}
case 'revise':openModal(`<h2 id="modal-title">把修改意见留在事项里</h2><p>${escapeHTML(t.title)}</p><label>需要调整的地方<textarea id="revision-note" rows="3" placeholder="描述期望的行为或结果"></textarea></label><div class="actions"><button class="button" data-action="close-modal">取消</button><button class="button primary" data-action="confirm-revise" data-id="${t.id}">提交修改意见</button></div>`);break;
case 'confirm-revise':{const note=document.getElementById('revision-note').value.trim();if(!note){document.getElementById('revision-note').focus();toast('请填写具体修改意见');return;}t.status='running';t.summary='正在处理你的修改意见：'+note;t.notes||=[];t.notes.push(note);addEvent(t,'用户 提出修改意见：'+note);t.fresh=false;save();closeModal();render();toast('修改意见已记录，事项继续推进');break;}
case 'decide':openModal(`<h2 id="modal-title">选择执行环境</h2><p>这次验证交给哪个环境？决定会保留在事项记录中。</p><button class="choice-option" data-action="confirm-decision" data-choice="本地 Runtime" data-id="${t.id}">本地 Runtime · 使用已连接设备</button><button class="choice-option" data-action="confirm-decision" data-choice="云端环境" data-id="${t.id}">云端环境 · 使用远程执行环境</button><div class="actions"><button class="button" data-action="close-modal">稍后决定</button></div>`);break;
case 'confirm-decision':t.status='running';t.summary='已选择'+b.dataset.choice+'，等待开始环境验证。';t.fresh=false;addEvent(t,'用户 选择了'+b.dataset.choice+'。');save();closeModal();render();toast('决定已记录，事项继续推进');break;
case 'artifact':openModal(`<h2 id="modal-title">${escapeHTML(t.artifacts[Number(b.dataset.index)]||'关联记录')}</h2><div class="demo-state">示例记录，用于体验结果如何随事项归档。</div><p><strong>事项：</strong>${escapeHTML(t.title)}</p><p><strong>目标：</strong>${escapeHTML(t.goal)}</p><p><strong>最新情况：</strong>${escapeHTML(t.summary)}</p><p>真实产品在这里展示对应版本、测试输出、代码差异或交付文件，保留可追溯来源。</p><div class="actions"><button class="button primary" data-action="close-modal">返回事项</button></div>`);break;
case 'track':send('帮我'+b.dataset.text,true);break;
}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-project]')){db.project=e.target.value;save();render();}if(e.target.matches('[data-chat-project]')){db.project=e.target.value;save();const span=document.querySelector('.context-pill>span');span.textContent='交办到：'+projectName(db.project);}});
document.addEventListener('input',e=>{if(e.target.id==='chat-input'){const context=taskById(route().id);db.drafts[chatKey(context?.id)]=e.target.value;save();}});
document.addEventListener('submit',e=>{if(e.target.id==='chat-form'){e.preventDefault();send(document.getElementById('chat-input').value);}});
document.addEventListener('keydown',e=>{if(modalRoot.firstChild){if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const els=[...modalRoot.querySelectorAll('button,input,textarea,a[href]')].filter(x=>!x.disabled);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}if(e.target.id==='chat-input'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(e.target.value);}});
window.addEventListener('hashchange',()=>{closeModal();render();window.scrollTo(0,0);});
if(!location.hash)history.replaceState(null,'','#/desk');
render();
