// Vocabulary declared by the installed dsh 0.1.5-rc.2 modules, captured 2026-09-13.
// chatty/* are the versioned Chatty automatic-approval plugin's log-only events.
// New required event types need an explicit adapter review; ignorable events retain their cursor.
enum DSHProtocol {
    static let sessionFormat = 3
    static let events: Set<String> = [
        "agent-preset/selected",
        "agent/inbox/spliced",
        "approval/asked",
        "approval/decided",
        "approval/policy",
        "assistant/attempt",
        "assistant/message",
        "chatty/approval-mode",
        "chatty/approval-review",
        "command/done",
        "command/run",
        "compaction/end",
        "compaction/prune",
        "compaction/start",
        "compaction/summary",
        "deliverables/presented",
        "feedback/message-delete",
        "feedback/message-put",
        "feedback/record",
        "goal/change",
        "hook/invoked",
        "hook/result",
        "llm/retry",
        "llm/retry-started",
        "model/selection",
        "permission/preset",
        "plan/mode",
        "request/context",
        "request/header",
        "sandbox/mode",
        "schedule/change",
        "session-log-deepseek/delivery-accepted",
        "session/end-seed",
        "session/title",
        "session/title-llm-request",
        "step/end",
        "step/start",
        "subagent/catalog",
        "subagent/descriptor",
        "subagent/model-selection-policy",
        "system/message",
        "todo/write",
        "tool-workflow/agent-end",
        "tool-workflow/agent-start",
        "tool-workflow/run-end",
        "tool-workflow/run-start",
        "tool/call",
        "tool/ptc-dispatch",
        "tool/ptc-dispatch-start",
        "tool/result",
        "turn/end",
        "turn/start",
        "user/message",
        "web/deepseek-search-llm-request",
    ]
}
